-- Seed inicial (generado desde public/providers.json)
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('vidcore','VidCore','https://vidcore.io/movie/{id}?autoPlay=true&sub=es','https://vidcore.io/tv/{id}/{s}/{e}?autoPlay=true&autoNext=true&nextButton=true&sub=es',false,true,'',true,0) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('embos','Embos','https://embos.top/movie/?mid={id}','https://embos.top/tv/?mid={id}&s={s}&e={e}',true,false,'',true,1) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('vidapi','VidAPI','https://vidapi.xyz/embed/movie/{id}','https://vidapi.xyz/embed/tv/{id}/{s}/{e}',false,false,'',true,2) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('streambetter','StreamBetter','https://streambetter.shop/filme/{id}','https://streambetter.shop/serie/{id}/{s}/{e}',true,false,'',true,3) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('vidzy','Vidzy','https://vidzy.org/movie/{id}?autoplay=1','https://vidzy.org/serie/{id}/{s}/{e}?autoplay=1&autonext=1',true,false,'',true,4) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('vimeus','Vimeus','https://vimeus.com/e/movie?{idparam}&view_key={key}&title=tvshow&theme=minimal&loader=v3&overlay=v3&splash=v3','https://vimeus.com/e/serie?{idparam}&se={s}&ep={e}&view_key={key}&title=tvshow&theme=minimal&loader=v3&overlay=v3&splash=v3',true,false,'',true,5) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('superembed','SuperEmbed','https://multiembed.mov/?video_id={id}{tmdbflag}','https://multiembed.mov/?video_id={id}{tmdbflag}&s={s}&e={e}',false,false,'',true,6) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('moviesapi','MoviesAPI','https://moviesapi.to/movie/{id}','https://moviesapi.to/tv/{id}/{s}/{e}',false,false,'',true,7) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('cinesrc','CineSrc','https://cinesrc.st/embed/movie/{id}','https://cinesrc.st/embed/tv/{id}?s={s}&e={e}',true,false,'',true,8) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('vidzee','VidZee','https://player.vidzee.wtf/embed/movie/{id}','https://player.vidzee.wtf/embed/tv/{id}/{s}/{e}',true,false,'',true,9) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('embedmovies','EmbedMovies','https://myembed.biz/filme/{id}','https://myembed.biz/serie/{id}/{s}/{e}',false,false,'',true,10) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('redeflix','RedeFlix','https://redeflixapi.store/filme/{id}','https://redeflixapi.store/serie/{id}/{s}/{e}',true,false,'',true,11) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('pipocacine','PipocaCine','https://pipocacine.lat/embed/{id}','https://pipocacine.lat/embed/{id}/{s}/{e}',true,false,'',true,12) on conflict (id) do nothing;
insert into providers (id,name,movie_tpl,tv_tpl,needs_tmdb,tv_ok,entry_key,active,ord) values ('megaembed','MegaEmbed','https://megaembed.com/embed/{id}','https://megaembed.com/embed/{id}/{s}/{e}',false,true,'',true,13) on conflict (id) do nothing;
insert into live_sources (id,name,format,list_url,active,ord) values ('streambetter','Streambetter PT','streambetter','https://streambetter.shop/api/channels?limit=60',true,0) on conflict (id) do nothing;
insert into live_sources (id,name,format,list_url,active,ord) values ('tvf90','Deportes ES','tvf90','https://tvf90.com/status.json',true,1) on conflict (id) do nothing;
insert into config (key,value) values ('providers_version','5') on conflict (key) do update set value=excluded.value;
