// Diccionario UI: español, inglés, portugués.
export type Lang = "es" | "en" | "pt";

const es = {
  nav_home: "INICIO", nav_movies: "PELÍCULAS", nav_series: "SERIES", nav_live: "TV EN VIVO", nav_list: "MI LISTA", nav_search: "BUSCAR",
  tabs_home: "Inicio", tabs_movies: "Pelis", tabs_series: "Series", tabs_live: "En vivo", tabs_list: "Mi lista", tabs_search: "Buscar",
  search_ph: "Buscar películas, series…", search_btn: "Buscar",
  feat: "Featured today", feat_kicker: "Contenido destacado",
  spotlight: "Episode Spotlight", toppicks: "Top picks", upcoming: "Upcoming", top10: "Top 10 on IMDb this week",
  movies: "Películas", series: "Series",
  ver_ahora: "VER AHORA", anadir: "+ AÑADIR", en_lista: "EN MI LISTA", ver_episodio: "Ver episodio",
  serie: "Serie", pelicula: "Película", movie: "Película", tv: "Serie",
  seguir: "Seguir viendo", limpiar: "Limpiar todo", limpiar_confirm: "¿Borrar todo Seguir viendo?",
  visto: "visto", iniciado: "iniciado", now: "ahora", min: "min", h: "h", d: "d", ago_m: "hace", ago_h: "hace", ago_d: "hace",
  mi_lista: "Mi lista", mi_lista_vacia: "Mi lista está vacía", mi_lista_hint: "Toca el corazón en cualquier tarjeta para guardarla aquí.",
  explorar: "Explorar", quitar: "Quitar", resultados: "Resultados",
  ver_ahora_btn: "Ver ahora", continuar: "Continuar", capitulos: "Capítulos", temporada_n: "Capítulos",
  sin_sinopsis: "Sin sinopsis.", sin_desc: "Sin descripción.",
  volver: "← Volver", servidor: "Servidor", siguiente: "Siguiente", todos_capitulos: "Capítulos",
  watch_note: "Si se queda cargando o da 404, cambia de servidor (algunos títulos no tienen fuente en todos).",
  resolving: "Resolviendo ID TMDB para", no_tmdb: "exige ID TMDB y no se pudo resolver para este título. Usa otro servidor.",
  falta_id: "Falta id",  list_error: "No se pudo cargar la lista de servidores.",  reintentar: "Reintentar",
  live_title: "TV en vivo", buscar_canal: "Buscar canal…", en_vivo: "EN VIVO", canales: "Canales", agenda: "Agenda deportiva",
  guia_error: "No se pudo cargar ninguna guía de canales.", ahora: "Ahora",
  fav_add: "Añadir a Mi lista", fav_remove: "Quitar de Mi lista", fav_in: "En Mi lista", fav_btn: "Mi lista",
  footer_dmca: "Política DMCA", footer_rights: "© 2026 TVShow. Todos los derechos reservados.",
  footer_love: "Por y para el amor de mi vida ❤️ NENA ❤️",
  love_q: "Una pregunta antes…", love_ask: "¿Cuál es el nombre de nuestra canción?",
  love_ph: "Escribe aquí…", love_wrong: "Esa no es… inténtalo de nuevo 💭",
  love_ok: "Correcto… esto es para ti ❤️", love_answer: "Responder", love_close: "Cerrar",
  dmca_title: "Política DMCA", dmca_updated: "Última actualización: septiembre 2026",
  dmca_h1: "1. No alojamos contenido",
  dmca_p1: "TVShow no aloja, almacena, transmite ni distribuye ningún archivo de video, audio o subtítulos en sus servidores. Somos un índice que enlaza pósters, sinopsis y metadatos (TMDB, Cinemeta, TVMaze) y reproduce contenido mediante reproductores de terceros incrustados (iframes). No tenemos control técnico ni editorial sobre esos reproductores externos.",
  dmca_h2: "2. A quién reclamar",
  dmca_p2: "Si eres titular de derechos y consideras que algún contenido vulnera tus derechos de autor, debes dirigir tu reclamación directamente al proveedor del reproductor correspondiente (el nombre del servidor aparece en la página de reproducción). Solo ellos pueden retirar el material, ya que reside en su infraestructura.",
  dmca_h3: "3. Avisos a TVShow",
  dmca_p3: "Aunque no alojamos material, atenderemos avisos bien fundamentados retirando los enlaces o accesos de nuestra interfaz cuando corresponda. Un aviso válido debe incluir:",
  dmca_li: ["Identificación de la obra protegida y del material supuestamente infractor (URL exacta dentro de TVShow).", "Tus datos de contacto (nombre, email).", "Declaración de buena fe de que el uso no está autorizado.", "Declaración, bajo pena de perjurio, de que actúas en nombre del titular.", "Firma física o electrónica."],
  dmca_h4: "4. Contranotificaciones",
  dmca_p4: "Si crees que un enlace fue retirado por error, puedes enviar una contranotificación con tus datos, la URL afectada y tu consentimiento a la jurisdicción competente. La restauraremos salvo que el reclamante acredite acción judicial en 10 días hábiles.",
  dmca_h5: "5. Reincidencia",
  dmca_p5: "Los proveedores o contenidos con reclamaciones reiteradas y fundadas serán eliminados de nuestros listados de forma permanente.",
  dmca_back: "← Volver al inicio",
  no_imdb: "· sin imdb_id", tv_t: "T", ep_e: "E",
  search_no_results: "Sin resultados",
  lang_label: "Idioma de la interfaz y sinopsis",
  det_seasons: "T", det_episodes: "E",
  score: "Puntuación", overview_h: "Vista general", cast_h: "Reparto principal",
  fact_estado: "Estado", fact_idioma: "Idioma original", fact_presupuesto: "Presupuesto", fact_ingresos: "Ingresos",
  ver_trailer: "Reproducir tráiler",
  gate_play: "Toca para reproducir",
  block_tip: "¿Ventanas emergentes? Bloquéalas con:",
  gate_title: "Acceso restringido", gate_hint: "Introduce tu código para ver los servidores.",
  gate_ph: "Tu código", gate_ok: "Entrar", gate_invalid: "Código inválido o caducado.", gate_revoked: "Código revocado.", gate_expired: "Código expirado.", gate_ref: "Ref", gate_contact: "Contacta al administrador para renovación.", gate_rate: "Demasiados intentos, espera un minuto.",
  abrir_externo: "Abrir externo",
  tv_hint: "Dentro del video mandan las flechas del reproductor · Atrás para salir",
  fullscreen: "Pantalla completa",
  popular: "Búsqueda popular", refresh: "Refresh", total: "Total",
  servidores_label: "Servidores",
  cargar_mas: "Cargar más", cargando: "Cargando…",
  crumb_detalle: "Detalle", crumb_persona: "Persona", crumb_genero: "Género", crumb_ver: "Ver",
};

export type Dict = typeof es;

const en: Dict = {
  nav_home: "HOME", nav_movies: "MOVIES", nav_series: "SERIES", nav_live: "LIVE TV", nav_list: "MY LIST", nav_search: "SEARCH",
  tabs_home: "Home", tabs_movies: "Movies", tabs_series: "Series", tabs_live: "Live", tabs_list: "My list", tabs_search: "Search",
  search_ph: "Search movies, series…", search_btn: "Search",
  feat: "Featured today", feat_kicker: "Featured",
  spotlight: "Episode Spotlight", toppicks: "Top picks", upcoming: "Upcoming", top10: "Top 10 on IMDb this week",
  movies: "Movies", series: "Series",
  ver_ahora: "WATCH NOW", anadir: "+ ADD", en_lista: "IN MY LIST", ver_episodio: "Watch episode",
  serie: "TV show", pelicula: "Movie", movie: "Movie", tv: "TV show",
  seguir: "Continue watching", limpiar: "Clear all", limpiar_confirm: "Clear all Continue watching?",
  visto: "watched", iniciado: "started", now: "now", min: "min", h: "h", d: "d", ago_m: "", ago_h: "", ago_d: "",
  mi_lista: "My list", mi_lista_vacia: "My list is empty", mi_lista_hint: "Tap the heart on any card to save it here.",
  explorar: "Explore", quitar: "Remove", resultados: "Results",
  ver_ahora_btn: "Watch now", continuar: "Continue", capitulos: "Episodes", temporada_n: "Episodes",
  sin_sinopsis: "No synopsis.", sin_desc: "No description.",
  volver: "← Back", servidor: "Server", siguiente: "Next", todos_capitulos: "Episodes",
  watch_note: "If it gets stuck loading or returns 404, switch servers (some titles lack sources on some).",
  resolving: "Resolving TMDB ID for", no_tmdb: "requires a TMDB ID which could not be resolved for this title. Try another server.",
  falta_id: "Missing id",  list_error: "Could not load the server list.",  reintentar: "Retry",
  live_title: "Live TV", buscar_canal: "Search channels…", en_vivo: "LIVE", canales: "Channels", agenda: "Sports guide",
  guia_error: "Could not load any channel guide.", ahora: "Now",
  fav_add: "Add to My list", fav_remove: "Remove from My list", fav_in: "In My list", fav_btn: "My list",
  footer_dmca: "DMCA Policy", footer_rights: "© 2026 TVShow. All rights reserved.",
  footer_love: "For and because of the love of my life ❤️ NENA ❤️",
  love_q: "One question first…", love_ask: "What is the name of our song?",
  love_ph: "Type here…", love_wrong: "That's not it… try again 💭",
  love_ok: "Correct… this is for you ❤️", love_answer: "Answer", love_close: "Close",
  dmca_title: "DMCA Policy", dmca_updated: "Last updated: September 2026",
  dmca_h1: "1. We host no content",
  dmca_p1: "TVShow does not host, store, transmit or distribute any video, audio or subtitle files on its servers. We are an index linking posters, synopses and metadata (TMDB, Cinemeta, TVMaze) and playing content through embedded third-party players (iframes). We have no technical or editorial control over those external players.",
  dmca_h2: "2. Who to contact",
  dmca_p2: "If you are a rights holder and believe any content infringes your copyright, address your claim directly to the corresponding player provider (the server name appears on the playback page). Only they can remove the material, as it resides on their infrastructure.",
  dmca_h3: "3. Notices to TVShow",
  dmca_p3: "Although we host no material, we will honor well-founded notices by removing links or access from our interface where appropriate. A valid notice must include:",
  dmca_li: ["Identification of the protected work and the allegedly infringing material (exact URL within TVShow).", "Your contact details (name, email).", "A good-faith statement that the use is unauthorized.", "A statement, under penalty of perjury, that you act on behalf of the owner.", "Physical or electronic signature."],
  dmca_h4: "4. Counter-notices",
  dmca_p4: "If you believe a link was removed by mistake, you may send a counter-notice with your details, the affected URL and your consent to the competent jurisdiction. We will restore it unless the claimant proves court action within 10 business days.",
  dmca_h5: "5. Repeat infringement",
  dmca_p5: "Providers or content with repeated, well-founded claims will be permanently removed from our listings.",
  dmca_back: "← Back to home",
  no_imdb: "· no imdb_id", tv_t: "S", ep_e: "E",
  search_no_results: "No results",
  lang_label: "Interface and synopsis language",
  det_seasons: "S", det_episodes: "E",
  score: "Score", overview_h: "Overview", cast_h: "Top cast",
  fact_estado: "Status", fact_idioma: "Original language", fact_presupuesto: "Budget", fact_ingresos: "Revenue",
  ver_trailer: "Play trailer",
  gate_play: "Tap to play",
  block_tip: "Pop-ups? Block them with:",
  gate_title: "Restricted access", gate_hint: "Enter your code to see the servers.",
  gate_ph: "Your code", gate_ok: "Enter", gate_invalid: "Invalid or expired code.", gate_revoked: "Code revoked.", gate_expired: "Code expired.", gate_ref: "Ref", gate_contact: "Contact the administrator to renew.", gate_rate: "Too many attempts, wait a minute.",
  abrir_externo: "Open externally",
  tv_hint: "Inside the video, the player's arrows rule · Back to exit",
  fullscreen: "Fullscreen",
  popular: "Popular search", refresh: "Refresh", total: "Total",
  servidores_label: "Servers",
  cargar_mas: "Load more", cargando: "Loading…",
  crumb_detalle: "Details", crumb_persona: "Person", crumb_genero: "Genre", crumb_ver: "Watch",
};

const pt: Dict = {
  nav_home: "INÍCIO", nav_movies: "FILMES", nav_series: "SÉRIES", nav_live: "TV AO VIVO", nav_list: "MINHA LISTA", nav_search: "BUSCAR",
  tabs_home: "Início", tabs_movies: "Filmes", tabs_series: "Séries", tabs_live: "Ao vivo", tabs_list: "Minha lista", tabs_search: "Buscar",
  search_ph: "Buscar filmes, séries…", search_btn: "Buscar",
  feat: "Destaques de hoje", feat_kicker: "Conteúdo em destaque",
  spotlight: "Episódio em destaque", toppicks: "Escolhas top", upcoming: "Em breve", top10: "Top 10 no IMDb esta semana",
  movies: "Filmes", series: "Séries",
  ver_ahora: "ASSISTIR", anadir: "+ ADICIONAR", en_lista: "NA MINHA LISTA", ver_episodio: "Ver episódio",
  serie: "Série", pelicula: "Filme", movie: "Filme", tv: "Série",
  seguir: "Continuar assistindo", limpiar: "Limpar tudo", limpiar_confirm: "Apagar tudo de Continuar assistindo?",
  visto: "visto", iniciado: "iniciado", now: "agora", min: "min", h: "h", d: "d", ago_m: "há", ago_h: "há", ago_d: "há",
  mi_lista: "Minha lista", mi_lista_vacia: "Minha lista está vazia", mi_lista_hint: "Toque no coração de qualquer cartão para salvá-lo aqui.",
  explorar: "Explorar", quitar: "Remover", resultados: "Resultados",
  ver_ahora_btn: "Assistir agora", continuar: "Continuar", capitulos: "Episódios", temporada_n: "Episódios",
  sin_sinopsis: "Sem sinopse.", sin_desc: "Sem descrição.",
  volver: "← Voltar", servidor: "Servidor", siguiente: "Próximo", todos_capitulos: "Episódios",
  watch_note: "Se travar carregando ou der 404, troque de servidor (alguns títulos não têm fonte em todos).",
  resolving: "Resolvendo ID TMDB para", no_tmdb: "exige ID TMDB que não pôde ser resolvido para este título. Tente outro servidor.",
  falta_id: "Falta id",  list_error: "Não foi possível carregar a lista de servidores.",  reintentar: "Tentar de novo",
  live_title: "TV ao vivo", buscar_canal: "Buscar canal…", en_vivo: "AO VIVO", canales: "Canais", agenda: "Agenda esportiva",
  guia_error: "Não foi possível carregar nenhum guia de canais.", ahora: "Agora",
  fav_add: "Adicionar à Minha lista", fav_remove: "Remover da Minha lista", fav_in: "Na Minha lista", fav_btn: "Minha lista",
  footer_dmca: "Política DMCA", footer_rights: "© 2026 TVShow. Todos os direitos reservados.",
  footer_love: "Por e para o amor da minha vida ❤️ NENA ❤️",
  love_q: "Uma pergunta antes…", love_ask: "Qual é o nome da nossa música?",
  love_ph: "Escreve aqui…", love_wrong: "Essa não é… tenta de novo 💭",
  love_ok: "Correto… isto é para ti ❤️", love_answer: "Responder", love_close: "Fechar",
  dmca_title: "Política DMCA", dmca_updated: "Última atualização: setembro de 2026",
  dmca_h1: "1. Não hospedamos conteúdo",
  dmca_p1: "O TVShow não hospeda, armazena, transmite nem distribui nenhum arquivo de vídeo, áudio ou legenda em seus servidores. Somos um índice que vincula pôsteres, sinopses e metadados (TMDB, Cinemeta, TVMaze) e reproduz conteúdo por meio de players de terceiros incorporados (iframes). Não temos controle técnico nem editorial sobre esses players externos.",
  dmca_h2: "2. A quem reclamar",
  dmca_p2: "Se você é titular de direitos e considera que algum conteúdo viola seus direitos autorais, dirija sua reclamação diretamente ao provedor do player correspondente (o nome do servidor aparece na página de reprodução). Somente eles podem remover o material, pois reside na infraestrutura deles.",
  dmca_h3: "3. Avisos ao TVShow",
  dmca_p3: "Embora não hospedemos material, atenderemos avisos bem fundamentados removendo os links ou acessos da nossa interface quando apropriado. Um aviso válido deve incluir:",
  dmca_li: ["Identificação da obra protegida e do material supostamente infrator (URL exata dentro do TVShow).", "Seus dados de contato (nome, email).", "Declaração de boa-fé de que o uso não é autorizado.", "Declaração, sob pena de perjúrio, de que age em nome do titular.", "Assinatura física ou eletrônica."],
  dmca_h4: "4. Contranotificações",
  dmca_p4: "Se você acredita que um link foi removido por engano, pode enviar uma contranotificação com seus dados, a URL afetada e seu consentimento à jurisdição competente. Vamos restaurá-lo, salvo se o reclamante comprovar ação judicial em 10 dias úteis.",
  dmca_h5: "5. Reincidência",
  dmca_p5: "Provedores ou conteúdos com reclamações reiteradas e fundamentadas serão eliminados permanentemente das nossas listas.",
  dmca_back: "← Voltar ao início",
  no_imdb: "· sem imdb_id", tv_t: "T", ep_e: "E",
  search_no_results: "Sem resultados",
  lang_label: "Idioma da interface e sinopses",
  det_seasons: "T", det_episodes: "E",
  score: "Pontuação", overview_h: "Sinopse", cast_h: "Elenco principal",
  fact_estado: "Estado", fact_idioma: "Idioma original", fact_presupuesto: "Orçamento", fact_ingresos: "Receita",
  ver_trailer: "Reproduzir trailer",
  gate_play: "Toca para reproduzir",
  block_tip: "Pop-ups? Bloqueie com:",
  gate_title: "Acesso restrito", gate_hint: "Digite seu código para ver os servidores.",
  gate_ph: "Seu código", gate_ok: "Entrar", gate_invalid: "Código inválido ou expirado.", gate_revoked: "Código revogado.", gate_expired: "Código expirado.", gate_ref: "Ref", gate_contact: "Entre em contato com o administrador para renovar.", gate_rate: "Muitas tentativas, aguarde um minuto.",
  abrir_externo: "Abrir externo",
  tv_hint: "Dentro do vídeo mandam as setas do player · Voltar para sair",
  fullscreen: "Tela cheia",
  popular: "Busca popular", refresh: "Refresh", total: "Total",
  servidores_label: "Servidores",
  cargar_mas: "Carregar mais", cargando: "Carregando…",
  crumb_detalle: "Detalhes", crumb_persona: "Pessoa", crumb_genero: "Gênero", crumb_ver: "Assistir",
};

export const STR: Record<Lang, Dict> = { es, en, pt };
export const t = (lang: Lang): Dict => STR[lang] || es;


